FI.WebAtividadeEntrevista/Controllers/BeneficiariosController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;
using Microsoft.Ajax.Utilities;
using System.Web.UI.WebControls;
using System.Reflection;

namespace WebAtividadeEntrevista.Controllers
{

    public class BeneficiariosController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(BeneficiarioModelDto dto)
        {
            BoBeneficiario bo = new BoBeneficiario();

            BeneficiarioModel model = new BeneficiarioModel(dto);
            BeneficiarioFilter filter = new BeneficiarioFilter();
            filter.CpfCliente = model.Cpf;
            filter.IdCliente = model.IdCliente;
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else if (bo.Listar(filter).Count > 0)
            {
                Response.StatusCode = 400;
                return Json("Cpf Já Existe em Nossa Base Por Favor Verificar");
            }
            else
            {

                model.Id = bo.Incluir(new Beneficiario()
                {
                    Id = model.Id,
                    Nome = model.Nome,
                    Cpf = model.Cpf,
                    IdCliente = model.IdCliente
                });
            }
            return Json(model);
        }


        [HttpGet]
        public JsonResult Listar(long idCliente)
        {
            try
            {
                BeneficiarioFilter beneficiarioFilter = new BeneficiarioFilter
                {
                    IdCliente = idCliente
                };
                List<Beneficiario> beneficiarios = new BoBeneficiario().Listar(beneficiarioFilter);

                return Json(beneficiarios, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Tratar o erro adequadamente
                throw;
            }
        }


    }  
}

FI.WebAtividadeEntrevista/Views/Beneficiarios/Forms.cshtml
    @*<head>
        <link rel="stylesheet" href="~/Content/Site.css" asp-append-version="true" />
    </head>*@
<body>
    <script src="~/Scripts/Clientes/mask.js" asp-append-version="true"></script>
    <div id="modalBeneficiarios" class="modal fade">
        <div class="modal-dialog">
            <div class="dialog-content">
                <div class="dialog-header">
                    <h4 class="modal-title">Beneficiários</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="dialog-body">
                    <div class="dialog-form-group">
                        <span class="input-cpf">
                            <label class="label-cpf" for="cpf">CPF:</label>
                            <input required="required"
                                   type="text"
                                   class="form-control"
                                   id="cpf-Beneficiario"
                                   name="cpf-Beneficiario"
                                   placeholder="Ex.: 010.011.111-100" maxlength="15">
                        </span>
                        <span class="input-nome">
                            <label class="label-cpf" for="Nacionalidade">Nacionalidade:</label>
                            <input required="required"
                                   type="text"
                                   class="form-control"
                                   id="Nacionalidade"
                                   name="Nacionalidade"
                                   placeholder="Ex.: brasileira"
                                   maxlength="50">
                        </span>
                        <span class="btn-incluir">
                            <button class="btn btn-md btn-success" onclick="salvar()">Incluir</button>
                        </span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

</body>


    
    

FI.WebAtividadeEntrevista/Views/Beneficiarios/Index.cshtml
@model IEnumerable<WebAtividadeEntrevista.Models.BeneficiarioModel>

<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Detalhes</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var beneficiario in Model)
        {
            <tr>
                <td>@beneficiario.Nome</td>
                <td>@beneficiario.CPF</td>
                <td>
                    <button class="btn btn-primary" data-toggle="modal" data-target="#myModal" data-url="@Url.Action("Detalhes", "Beneficiarios", new { id = beneficiario.Id })">
                        Detalhes
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>

<script>$(document).ready(function() {
        $('.btn-primary').on('click', function() {
            var url = $(this).data('url');
            $('#myModal .modal-content').load(url);
        });
    });</script>